version: '3.4'

networks:
  graphql_upload:

volumes:
  graphql_upload:

services:
  graphql_upload:
    container_name: graphql_upload
    image: graphql_upload
    build: .
    networks:
      - graphql_upload
    environment:
      - IPFS_ENDPOINT
      - IPFS_CLIENT_ENDPOINT
      - IPFS_MAX_FILE_SIZE
    depends_on:
      - ipfs_server
    restart: always
    ports:
      - 3002:3000
    command: sh -c "npm run start"
    volumes:
      - graphql_upload:/usr/src/app/config

  ipfs_server:
    container_name: ipfs_server
    image: ipfs/go-ipfs
    networks:
      - graphql_upload
    restart: always
    ports:
      - 4001:4001/tcp
      - 4002:4002/udp
      - 127.0.0.1:5001:5001
      - 8080:8080
    volumes:
      - /tmp/ipfs-docker-data:/data/ipfs
